set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH5_DQ[0]}]
set_property PACKAGE_PIN B5 [get_ports {IO_NAND_CH5_DQ[0]}]
set_property SLEW FAST [get_ports {IO_NAND_CH5_DQ[0]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH5_DQ[0]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH5_DQ[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH5_DQ[1]}]
set_property PACKAGE_PIN B4 [get_ports {IO_NAND_CH5_DQ[1]}]
set_property SLEW FAST [get_ports {IO_NAND_CH5_DQ[1]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH5_DQ[1]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH5_DQ[1]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH5_DQ[2]}]
set_property PACKAGE_PIN C2 [get_ports {IO_NAND_CH5_DQ[2]}]
set_property SLEW FAST [get_ports {IO_NAND_CH5_DQ[2]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH5_DQ[2]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH5_DQ[2]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH5_DQ[3]}]
set_property PACKAGE_PIN C1 [get_ports {IO_NAND_CH5_DQ[3]}]
set_property SLEW FAST [get_ports {IO_NAND_CH5_DQ[3]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH5_DQ[3]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH5_DQ[3]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH5_DQ[4]}]
set_property PACKAGE_PIN B2 [get_ports {IO_NAND_CH5_DQ[4]}]
set_property SLEW FAST [get_ports {IO_NAND_CH5_DQ[4]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH5_DQ[4]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH5_DQ[4]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH5_DQ[5]}]
set_property PACKAGE_PIN B1 [get_ports {IO_NAND_CH5_DQ[5]}]
set_property SLEW FAST [get_ports {IO_NAND_CH5_DQ[5]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH5_DQ[5]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH5_DQ[5]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH5_DQ[6]}]
set_property PACKAGE_PIN A3 [get_ports {IO_NAND_CH5_DQ[6]}]
set_property SLEW FAST [get_ports {IO_NAND_CH5_DQ[6]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH5_DQ[6]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH5_DQ[6]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH5_DQ[7]}]
set_property PACKAGE_PIN A2 [get_ports {IO_NAND_CH5_DQ[7]}]
set_property SLEW FAST [get_ports {IO_NAND_CH5_DQ[7]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH5_DQ[7]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH5_DQ[7]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH5_CE[0]}]
set_property PACKAGE_PIN H12 [get_ports {O_NAND_CH5_CE[0]}]
set_property SLEW SLOW [get_ports {O_NAND_CH5_CE[0]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH5_CE[0]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH5_CE[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH5_CE[1]}]
set_property PACKAGE_PIN G11 [get_ports {O_NAND_CH5_CE[1]}]
set_property SLEW SLOW [get_ports {O_NAND_CH5_CE[1]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH5_CE[1]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH5_CE[1]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH5_CE[2]}]
set_property PACKAGE_PIN E10 [get_ports {O_NAND_CH5_CE[2]}]
set_property SLEW SLOW [get_ports {O_NAND_CH5_CE[2]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH5_CE[2]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH5_CE[2]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH5_CE[3]}]
set_property PACKAGE_PIN D10 [get_ports {O_NAND_CH5_CE[3]}]
set_property SLEW SLOW [get_ports {O_NAND_CH5_CE[3]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH5_CE[3]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH5_CE[3]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH5_CE[4]}]
set_property PACKAGE_PIN B10 [get_ports {O_NAND_CH5_CE[4]}]
set_property SLEW SLOW [get_ports {O_NAND_CH5_CE[4]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH5_CE[4]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH5_CE[4]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH5_CE[5]}]
set_property PACKAGE_PIN A10 [get_ports {O_NAND_CH5_CE[5]}]
set_property SLEW SLOW [get_ports {O_NAND_CH5_CE[5]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH5_CE[5]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH5_CE[5]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH5_CE[6]}]
set_property PACKAGE_PIN B9 [get_ports {O_NAND_CH5_CE[6]}]
set_property SLEW SLOW [get_ports {O_NAND_CH5_CE[6]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH5_CE[6]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH5_CE[6]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH5_CE[7]}]
set_property PACKAGE_PIN A9 [get_ports {O_NAND_CH5_CE[7]}]
set_property SLEW SLOW [get_ports {O_NAND_CH5_CE[7]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH5_CE[7]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH5_CE[7]}]

set_property IOSTANDARD SSTL18_II [get_ports O_NAND_CH5_CLE]
set_property PACKAGE_PIN D1 [get_ports O_NAND_CH5_CLE]
set_property SLEW FAST [get_ports O_NAND_CH5_CLE]
#set_property DRIVE 8 [get_ports O_NAND_CH5_CLE]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH5_CLE]

set_property IOSTANDARD SSTL18_II [get_ports O_NAND_CH5_ALE]
set_property PACKAGE_PIN C4 [get_ports O_NAND_CH5_ALE]
set_property SLEW FAST [get_ports O_NAND_CH5_ALE]
#set_property DRIVE 8 [get_ports O_NAND_CH5_ALE]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH5_ALE]

set_property IOSTANDARD SSTL18_II [get_ports O_NAND_CH5_WE]
set_property PACKAGE_PIN E11 [get_ports O_NAND_CH5_WE]
set_property SLEW FAST [get_ports O_NAND_CH5_WE]
#set_property DRIVE 8 [get_ports O_NAND_CH5_WE]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH5_WE]

set_property IOSTANDARD DIFF_SSTL18_II [get_ports O_NAND_CH5_RE_P]
set_property PACKAGE_PIN A5 [get_ports O_NAND_CH5_RE_P]
set_property SLEW FAST [get_ports O_NAND_CH5_RE_P]
#set_property DRIVE 8 [get_ports O_NAND_CH5_RE_P]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH5_RE_P]

set_property IOSTANDARD DIFF_SSTL18_II [get_ports O_NAND_CH5_RE_N]
set_property PACKAGE_PIN A4 [get_ports O_NAND_CH5_RE_N]
set_property SLEW FAST [get_ports O_NAND_CH5_RE_N]
#set_property DRIVE 8 [get_ports O_NAND_CH5_RE_N]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH5_RE_N]

set_property IOSTANDARD DIFF_SSTL18_II [get_ports IO_NAND_CH5_DQS_P]
set_property PACKAGE_PIN F4 [get_ports IO_NAND_CH5_DQS_P]
set_property SLEW FAST [get_ports IO_NAND_CH5_DQS_P]
#set_property DRIVE 8 [get_ports IO_NAND_CH5_DQS_P]
#set_property PIO_DIRECTION BIDIR [get_ports IO_NAND_CH5_DQS_P]

set_property IOSTANDARD DIFF_SSTL18_II [get_ports IO_NAND_CH5_DQS_N]
set_property PACKAGE_PIN F3 [get_ports IO_NAND_CH5_DQS_N]
set_property SLEW FAST [get_ports IO_NAND_CH5_DQS_N]
#set_property DRIVE 8 [get_ports IO_NAND_CH5_DQS_N]
#set_property PIO_DIRECTION BIDIR [get_ports IO_NAND_CH5_DQS_N]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH5_RB[0]}]
set_property PACKAGE_PIN A7 [get_ports {I_NAND_CH5_RB[0]}]
set_property SLEW FAST [get_ports {I_NAND_CH5_RB[0]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH5_RB[0]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH5_RB[0]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH5_RB[1]}]
set_property PACKAGE_PIN C7 [get_ports {I_NAND_CH5_RB[1]}]
set_property SLEW FAST [get_ports {I_NAND_CH5_RB[1]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH5_RB[1]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH5_RB[1]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH5_RB[2]}]
set_property PACKAGE_PIN B7 [get_ports {I_NAND_CH5_RB[2]}]
set_property SLEW FAST [get_ports {I_NAND_CH5_RB[2]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH5_RB[2]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH5_RB[2]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH5_RB[3]}]
set_property PACKAGE_PIN C6 [get_ports {I_NAND_CH5_RB[3]}]
set_property SLEW FAST [get_ports {I_NAND_CH5_RB[3]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH5_RB[3]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH5_RB[3]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH5_RB[4]}]
set_property PACKAGE_PIN B6 [get_ports {I_NAND_CH5_RB[4]}]
set_property SLEW FAST [get_ports {I_NAND_CH5_RB[4]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH5_RB[4]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH5_RB[4]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH5_RB[5]}]
set_property PACKAGE_PIN C9 [get_ports {I_NAND_CH5_RB[5]}]
set_property SLEW FAST [get_ports {I_NAND_CH5_RB[5]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH5_RB[5]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH5_RB[5]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH5_RB[6]}]
set_property PACKAGE_PIN J11 [get_ports {I_NAND_CH5_RB[6]}]
set_property SLEW FAST [get_ports {I_NAND_CH5_RB[6]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH5_RB[6]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH5_RB[6]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH5_RB[7]}]
set_property PACKAGE_PIN H11 [get_ports {I_NAND_CH5_RB[7]}]
set_property SLEW FAST [get_ports {I_NAND_CH5_RB[7]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH5_RB[7]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH5_RB[7]}]

set_property IOSTANDARD LVCMOS18 [get_ports O_NAND_CH5_WP]
set_property PACKAGE_PIN L4 [get_ports O_NAND_CH5_WP]
set_property SLEW SLOW [get_ports O_NAND_CH5_WP]
#set_property DRIVE 8 [get_ports O_NAND_CH5_WP]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH5_WP]
