set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH4_DQ[0]}]
set_property PACKAGE_PIN J4 [get_ports {IO_NAND_CH4_DQ[0]}]
set_property SLEW FAST [get_ports {IO_NAND_CH4_DQ[0]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH4_DQ[0]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH4_DQ[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH4_DQ[1]}]
set_property PACKAGE_PIN J3 [get_ports {IO_NAND_CH4_DQ[1]}]
set_property SLEW FAST [get_ports {IO_NAND_CH4_DQ[1]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH4_DQ[1]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH4_DQ[1]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH4_DQ[2]}]
set_property PACKAGE_PIN L1 [get_ports {IO_NAND_CH4_DQ[2]}]
set_property SLEW FAST [get_ports {IO_NAND_CH4_DQ[2]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH4_DQ[2]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH4_DQ[2]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH4_DQ[3]}]
set_property PACKAGE_PIN K1 [get_ports {IO_NAND_CH4_DQ[3]}]
set_property SLEW FAST [get_ports {IO_NAND_CH4_DQ[3]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH4_DQ[3]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH4_DQ[3]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH4_DQ[4]}]
set_property PACKAGE_PIN L3 [get_ports {IO_NAND_CH4_DQ[4]}]
set_property SLEW FAST [get_ports {IO_NAND_CH4_DQ[4]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH4_DQ[4]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH4_DQ[4]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH4_DQ[5]}]
set_property PACKAGE_PIN L2 [get_ports {IO_NAND_CH4_DQ[5]}]
set_property SLEW FAST [get_ports {IO_NAND_CH4_DQ[5]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH4_DQ[5]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH4_DQ[5]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH4_DQ[6]}]
set_property PACKAGE_PIN K5 [get_ports {IO_NAND_CH4_DQ[6]}]
set_property SLEW FAST [get_ports {IO_NAND_CH4_DQ[6]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH4_DQ[6]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH4_DQ[6]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH4_DQ[7]}]
set_property PACKAGE_PIN J5 [get_ports {IO_NAND_CH4_DQ[7]}]
set_property SLEW FAST [get_ports {IO_NAND_CH4_DQ[7]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH4_DQ[7]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH4_DQ[7]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH4_CE[0]}]
set_property PACKAGE_PIN E5 [get_ports {O_NAND_CH4_CE[0]}]
set_property SLEW SLOW [get_ports {O_NAND_CH4_CE[0]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH4_CE[0]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH4_CE[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH4_CE[1]}]
set_property PACKAGE_PIN E6 [get_ports {O_NAND_CH4_CE[1]}]
set_property SLEW SLOW [get_ports {O_NAND_CH4_CE[1]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH4_CE[1]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH4_CE[1]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH4_CE[2]}]
set_property PACKAGE_PIN D5 [get_ports {O_NAND_CH4_CE[2]}]
set_property SLEW SLOW [get_ports {O_NAND_CH4_CE[2]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH4_CE[2]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH4_CE[2]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH4_CE[3]}]
set_property PACKAGE_PIN D4 [get_ports {O_NAND_CH4_CE[3]}]
set_property SLEW SLOW [get_ports {O_NAND_CH4_CE[3]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH4_CE[3]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH4_CE[3]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH4_CE[4]}]
set_property PACKAGE_PIN D3 [get_ports {O_NAND_CH4_CE[4]}]
set_property SLEW SLOW [get_ports {O_NAND_CH4_CE[4]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH4_CE[4]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH4_CE[4]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH4_CE[5]}]
set_property PACKAGE_PIN E3 [get_ports {O_NAND_CH4_CE[5]}]
set_property SLEW SLOW [get_ports {O_NAND_CH4_CE[5]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH4_CE[5]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH4_CE[5]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH4_CE[6]}]
set_property PACKAGE_PIN E2 [get_ports {O_NAND_CH4_CE[6]}]
set_property SLEW SLOW [get_ports {O_NAND_CH4_CE[6]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH4_CE[6]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH4_CE[6]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH4_CE[7]}]
set_property PACKAGE_PIN E1 [get_ports {O_NAND_CH4_CE[7]}]
set_property SLEW SLOW [get_ports {O_NAND_CH4_CE[7]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH4_CE[7]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH4_CE[7]}]

set_property IOSTANDARD SSTL18_II [get_ports O_NAND_CH4_CLE]
set_property PACKAGE_PIN H6 [get_ports O_NAND_CH4_CLE]
set_property SLEW FAST [get_ports O_NAND_CH4_CLE]
#set_property DRIVE 8 [get_ports O_NAND_CH4_CLE]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH4_CLE]

set_property IOSTANDARD SSTL18_II [get_ports O_NAND_CH4_ALE]
set_property PACKAGE_PIN G6 [get_ports O_NAND_CH4_ALE]
set_property SLEW FAST [get_ports O_NAND_CH4_ALE]
#set_property DRIVE 8 [get_ports O_NAND_CH4_ALE]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH4_ALE]

set_property IOSTANDARD SSTL18_II [get_ports O_NAND_CH4_WE]
set_property PACKAGE_PIN G2 [get_ports O_NAND_CH4_WE]
set_property SLEW FAST [get_ports O_NAND_CH4_WE]
#set_property DRIVE 8 [get_ports O_NAND_CH4_WE]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH4_WE]

set_property IOSTANDARD DIFF_SSTL18_II [get_ports O_NAND_CH4_RE_P]
set_property PACKAGE_PIN K3 [get_ports O_NAND_CH4_RE_P]
set_property SLEW FAST [get_ports O_NAND_CH4_RE_P]
#set_property DRIVE 8 [get_ports O_NAND_CH4_RE_P]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH4_RE_P]

set_property IOSTANDARD DIFF_SSTL18_II [get_ports O_NAND_CH4_RE_N]
set_property PACKAGE_PIN K2 [get_ports O_NAND_CH4_RE_N]
set_property SLEW FAST [get_ports O_NAND_CH4_RE_N]
#set_property DRIVE 8 [get_ports O_NAND_CH4_RE_N]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH4_RE_N]

set_property IOSTANDARD DIFF_SSTL18_II [get_ports IO_NAND_CH4_DQS_P]
set_property PACKAGE_PIN H4 [get_ports IO_NAND_CH4_DQS_P]
set_property SLEW FAST [get_ports IO_NAND_CH4_DQS_P]
#set_property DRIVE 8 [get_ports IO_NAND_CH4_DQS_P]
#set_property PIO_DIRECTION BIDIR [get_ports IO_NAND_CH4_DQS_P]

set_property IOSTANDARD DIFF_SSTL18_II [get_ports IO_NAND_CH4_DQS_N]
set_property PACKAGE_PIN H3 [get_ports IO_NAND_CH4_DQS_N]
set_property SLEW FAST [get_ports IO_NAND_CH4_DQS_N]
#set_property DRIVE 8 [get_ports IO_NAND_CH4_DQS_N]
#set_property PIO_DIRECTION BIDIR [get_ports IO_NAND_CH4_DQS_N]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH4_RB[0]}]
set_property PACKAGE_PIN L5 [get_ports {I_NAND_CH4_RB[0]}]
set_property SLEW FAST [get_ports {I_NAND_CH4_RB[0]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH4_RB[0]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH4_RB[0]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH4_RB[1]}]
set_property PACKAGE_PIN J1 [get_ports {I_NAND_CH4_RB[1]}]
set_property SLEW FAST [get_ports {I_NAND_CH4_RB[1]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH4_RB[1]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH4_RB[1]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH4_RB[2]}]
set_property PACKAGE_PIN H1 [get_ports {I_NAND_CH4_RB[2]}]
set_property SLEW FAST [get_ports {I_NAND_CH4_RB[2]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH4_RB[2]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH4_RB[2]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH4_RB[3]}]
set_property PACKAGE_PIN H2 [get_ports {I_NAND_CH4_RB[3]}]
set_property SLEW FAST [get_ports {I_NAND_CH4_RB[3]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH4_RB[3]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH4_RB[3]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH4_RB[4]}]
set_property PACKAGE_PIN G1 [get_ports {I_NAND_CH4_RB[4]}]
set_property SLEW FAST [get_ports {I_NAND_CH4_RB[4]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH4_RB[4]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH4_RB[4]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH4_RB[5]}]
set_property PACKAGE_PIN G5 [get_ports {I_NAND_CH4_RB[5]}]
set_property SLEW FAST [get_ports {I_NAND_CH4_RB[5]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH4_RB[5]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH4_RB[5]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH4_RB[6]}]
set_property PACKAGE_PIN G4 [get_ports {I_NAND_CH4_RB[6]}]
set_property SLEW FAST [get_ports {I_NAND_CH4_RB[6]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH4_RB[6]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH4_RB[6]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH4_RB[7]}]
set_property PACKAGE_PIN F5 [get_ports {I_NAND_CH4_RB[7]}]
set_property SLEW FAST [get_ports {I_NAND_CH4_RB[7]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH4_RB[7]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH4_RB[7]}]

set_property IOSTANDARD LVCMOS18 [get_ports O_NAND_CH4_WP]
set_property PACKAGE_PIN K6 [get_ports O_NAND_CH4_WP]
set_property SLEW SLOW [get_ports O_NAND_CH4_WP]
#set_property DRIVE 8 [get_ports O_NAND_CH4_WP]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH4_WP]
