set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH6_DQ[0]}]
set_property PACKAGE_PIN K12 [get_ports {IO_NAND_CH6_DQ[0]}]
set_property SLEW FAST [get_ports {IO_NAND_CH6_DQ[0]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH6_DQ[0]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH6_DQ[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH6_DQ[1]}]
set_property PACKAGE_PIN L12 [get_ports {IO_NAND_CH6_DQ[1]}]
set_property SLEW FAST [get_ports {IO_NAND_CH6_DQ[1]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH6_DQ[1]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH6_DQ[1]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH6_DQ[2]}]
set_property PACKAGE_PIN L9 [get_ports {IO_NAND_CH6_DQ[2]}]
set_property SLEW FAST [get_ports {IO_NAND_CH6_DQ[2]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH6_DQ[2]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH6_DQ[2]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH6_DQ[3]}]
set_property PACKAGE_PIN L10 [get_ports {IO_NAND_CH6_DQ[3]}]
set_property SLEW FAST [get_ports {IO_NAND_CH6_DQ[3]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH6_DQ[3]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH6_DQ[3]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH6_DQ[4]}]
set_property PACKAGE_PIN K10 [get_ports {IO_NAND_CH6_DQ[4]}]
set_property SLEW FAST [get_ports {IO_NAND_CH6_DQ[4]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH6_DQ[4]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH6_DQ[4]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH6_DQ[5]}]
set_property PACKAGE_PIN K11 [get_ports {IO_NAND_CH6_DQ[5]}]
set_property SLEW FAST [get_ports {IO_NAND_CH6_DQ[5]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH6_DQ[5]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH6_DQ[5]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH6_DQ[6]}]
set_property PACKAGE_PIN J9 [get_ports {IO_NAND_CH6_DQ[6]}]
set_property SLEW FAST [get_ports {IO_NAND_CH6_DQ[6]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH6_DQ[6]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH6_DQ[6]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH6_DQ[7]}]
set_property PACKAGE_PIN J10 [get_ports {IO_NAND_CH6_DQ[7]}]
set_property SLEW FAST [get_ports {IO_NAND_CH6_DQ[7]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH6_DQ[7]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH6_DQ[7]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH6_CE[0]}]
set_property PACKAGE_PIN H9 [get_ports {O_NAND_CH6_CE[0]}]
set_property SLEW SLOW [get_ports {O_NAND_CH6_CE[0]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH6_CE[0]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH6_CE[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH6_CE[1]}]
set_property PACKAGE_PIN L13 [get_ports {O_NAND_CH6_CE[1]}]
set_property SLEW SLOW [get_ports {O_NAND_CH6_CE[1]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH6_CE[1]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH6_CE[1]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH6_CE[2]}]
set_property PACKAGE_PIN G9 [get_ports {O_NAND_CH6_CE[2]}]
set_property SLEW SLOW [get_ports {O_NAND_CH6_CE[2]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH6_CE[2]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH6_CE[2]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH6_CE[3]}]
set_property PACKAGE_PIN J8 [get_ports {O_NAND_CH6_CE[3]}]
set_property SLEW SLOW [get_ports {O_NAND_CH6_CE[3]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH6_CE[3]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH6_CE[3]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH6_CE[4]}]
set_property PACKAGE_PIN H8 [get_ports {O_NAND_CH6_CE[4]}]
set_property SLEW SLOW [get_ports {O_NAND_CH6_CE[4]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH6_CE[4]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH6_CE[4]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH6_CE[5]}]
set_property PACKAGE_PIN F8 [get_ports {O_NAND_CH6_CE[5]}]
set_property SLEW SLOW [get_ports {O_NAND_CH6_CE[5]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH6_CE[5]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH6_CE[5]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH6_CE[6]}]
set_property PACKAGE_PIN F7 [get_ports {O_NAND_CH6_CE[6]}]
set_property SLEW SLOW [get_ports {O_NAND_CH6_CE[6]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH6_CE[6]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH6_CE[6]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH6_CE[7]}]
set_property PACKAGE_PIN E7 [get_ports {O_NAND_CH6_CE[7]}]
set_property SLEW SLOW [get_ports {O_NAND_CH6_CE[7]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH6_CE[7]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH6_CE[7]}]

set_property IOSTANDARD SSTL18_II [get_ports O_NAND_CH6_CLE]
set_property PACKAGE_PIN D6 [get_ports O_NAND_CH6_CLE]
set_property SLEW FAST [get_ports O_NAND_CH6_CLE]
#set_property DRIVE 8 [get_ports O_NAND_CH6_CLE]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH6_CLE]

set_property IOSTANDARD SSTL18_II [get_ports O_NAND_CH6_ALE]
set_property PACKAGE_PIN L7 [get_ports O_NAND_CH6_ALE]
set_property SLEW FAST [get_ports O_NAND_CH6_ALE]
#set_property DRIVE 8 [get_ports O_NAND_CH6_ALE]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH6_ALE]

set_property IOSTANDARD SSTL18_II [get_ports O_NAND_CH6_WE]
set_property PACKAGE_PIN H7 [get_ports O_NAND_CH6_WE]
set_property SLEW FAST [get_ports O_NAND_CH6_WE]
#set_property DRIVE 8 [get_ports O_NAND_CH6_WE]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH6_WE]

set_property IOSTANDARD DIFF_SSTL18_II [get_ports O_NAND_CH6_RE_P]
set_property PACKAGE_PIN L8 [get_ports O_NAND_CH6_RE_P]
set_property SLEW FAST [get_ports O_NAND_CH6_RE_P]
#set_property DRIVE 8 [get_ports O_NAND_CH6_RE_P]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH6_RE_P]

set_property IOSTANDARD DIFF_SSTL18_II [get_ports O_NAND_CH6_RE_N]
set_property PACKAGE_PIN K8 [get_ports O_NAND_CH6_RE_N]
set_property SLEW FAST [get_ports O_NAND_CH6_RE_N]
#set_property DRIVE 8 [get_ports O_NAND_CH6_RE_N]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH6_RE_N]

set_property IOSTANDARD DIFF_SSTL18_II [get_ports IO_NAND_CH6_DQS_P]
set_property PACKAGE_PIN F9 [get_ports IO_NAND_CH6_DQS_P]
set_property SLEW FAST [get_ports IO_NAND_CH6_DQS_P]
#set_property DRIVE 8 [get_ports IO_NAND_CH6_DQS_P]
#set_property PIO_DIRECTION BIDIR [get_ports IO_NAND_CH6_DQS_P]

set_property IOSTANDARD DIFF_SSTL18_II [get_ports IO_NAND_CH6_DQS_N]
set_property PACKAGE_PIN E8 [get_ports IO_NAND_CH6_DQS_N]
set_property SLEW FAST [get_ports IO_NAND_CH6_DQS_N]
#set_property DRIVE 8 [get_ports IO_NAND_CH6_DQS_N]
#set_property PIO_DIRECTION BIDIR [get_ports IO_NAND_CH6_DQS_N]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH6_RB[0]}]
set_property PACKAGE_PIN G10 [get_ports {I_NAND_CH6_RB[0]}]
set_property SLEW FAST [get_ports {I_NAND_CH6_RB[0]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH6_RB[0]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH6_RB[0]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH6_RB[1]}]
set_property PACKAGE_PIN F10 [get_ports {I_NAND_CH6_RB[1]}]
set_property SLEW FAST [get_ports {I_NAND_CH6_RB[1]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH6_RB[1]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH6_RB[1]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH6_RB[2]}]
set_property PACKAGE_PIN D9 [get_ports {I_NAND_CH6_RB[2]}]
set_property SLEW FAST [get_ports {I_NAND_CH6_RB[2]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH6_RB[2]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH6_RB[2]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH6_RB[3]}]
set_property PACKAGE_PIN D8 [get_ports {I_NAND_CH6_RB[3]}]
set_property SLEW FAST [get_ports {I_NAND_CH6_RB[3]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH6_RB[3]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH6_RB[3]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH6_RB[4]}]
set_property PACKAGE_PIN L15 [get_ports {I_NAND_CH6_RB[4]}]
set_property SLEW FAST [get_ports {I_NAND_CH6_RB[4]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH6_RB[4]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH6_RB[4]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH6_RB[5]}]
set_property PACKAGE_PIN L14 [get_ports {I_NAND_CH6_RB[5]}]
set_property SLEW FAST [get_ports {I_NAND_CH6_RB[5]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH6_RB[5]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH6_RB[5]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH6_RB[6]}]
set_property PACKAGE_PIN J13 [get_ports {I_NAND_CH6_RB[6]}]
set_property SLEW FAST [get_ports {I_NAND_CH6_RB[6]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH6_RB[6]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH6_RB[6]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH6_RB[7]}]
set_property PACKAGE_PIN H13 [get_ports {I_NAND_CH6_RB[7]}]
set_property SLEW FAST [get_ports {I_NAND_CH6_RB[7]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH6_RB[7]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH6_RB[7]}]

set_property IOSTANDARD LVCMOS18 [get_ports O_NAND_CH6_WP]
set_property PACKAGE_PIN K16 [get_ports O_NAND_CH6_WP]
set_property SLEW SLOW [get_ports O_NAND_CH6_WP]
#set_property DRIVE 8 [get_ports O_NAND_CH6_WP]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH6_WP]
