set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH7_DQ[0]}]
set_property PACKAGE_PIN A17 [get_ports {IO_NAND_CH7_DQ[0]}]
set_property SLEW FAST [get_ports {IO_NAND_CH7_DQ[0]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH7_DQ[0]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH7_DQ[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH7_DQ[1]}]
set_property PACKAGE_PIN B17 [get_ports {IO_NAND_CH7_DQ[1]}]
set_property SLEW FAST [get_ports {IO_NAND_CH7_DQ[1]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH7_DQ[1]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH7_DQ[1]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH7_DQ[2]}]
set_property PACKAGE_PIN C17 [get_ports {IO_NAND_CH7_DQ[2]}]
set_property SLEW FAST [get_ports {IO_NAND_CH7_DQ[2]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH7_DQ[2]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH7_DQ[2]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH7_DQ[3]}]
set_property PACKAGE_PIN B16 [get_ports {IO_NAND_CH7_DQ[3]}]
set_property SLEW FAST [get_ports {IO_NAND_CH7_DQ[3]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH7_DQ[3]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH7_DQ[3]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH7_DQ[4]}]
set_property PACKAGE_PIN D16 [get_ports {IO_NAND_CH7_DQ[4]}]
set_property SLEW FAST [get_ports {IO_NAND_CH7_DQ[4]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH7_DQ[4]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH7_DQ[4]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH7_DQ[5]}]
set_property PACKAGE_PIN C16 [get_ports {IO_NAND_CH7_DQ[5]}]
set_property SLEW FAST [get_ports {IO_NAND_CH7_DQ[5]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH7_DQ[5]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH7_DQ[5]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH7_DQ[6]}]
set_property PACKAGE_PIN E15 [get_ports {IO_NAND_CH7_DQ[6]}]
set_property SLEW FAST [get_ports {IO_NAND_CH7_DQ[6]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH7_DQ[6]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH7_DQ[6]}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_CH7_DQ[7]}]
set_property PACKAGE_PIN E16 [get_ports {IO_NAND_CH7_DQ[7]}]
set_property SLEW FAST [get_ports {IO_NAND_CH7_DQ[7]}]
#set_property DRIVE 8 [get_ports {IO_NAND_CH7_DQ[7]}]
#set_property PIO_DIRECTION BIDIR [get_ports {IO_NAND_CH7_DQ[7]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH7_CE[0]}]
set_property PACKAGE_PIN G17 [get_ports {O_NAND_CH7_CE[0]}]
set_property SLEW SLOW [get_ports {O_NAND_CH7_CE[0]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH7_CE[0]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH7_CE[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH7_CE[1]}]
set_property PACKAGE_PIN G16 [get_ports {O_NAND_CH7_CE[1]}]
set_property SLEW SLOW [get_ports {O_NAND_CH7_CE[1]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH7_CE[1]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH7_CE[1]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH7_CE[2]}]
set_property PACKAGE_PIN G15 [get_ports {O_NAND_CH7_CE[2]}]
set_property SLEW SLOW [get_ports {O_NAND_CH7_CE[2]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH7_CE[2]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH7_CE[2]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH7_CE[3]}]
set_property PACKAGE_PIN G14 [get_ports {O_NAND_CH7_CE[3]}]
set_property SLEW SLOW [get_ports {O_NAND_CH7_CE[3]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH7_CE[3]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH7_CE[3]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH7_CE[4]}]
set_property PACKAGE_PIN G12 [get_ports {O_NAND_CH7_CE[4]}]
set_property SLEW SLOW [get_ports {O_NAND_CH7_CE[4]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH7_CE[4]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH7_CE[4]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH7_CE[5]}]
set_property PACKAGE_PIN F12 [get_ports {O_NAND_CH7_CE[5]}]
set_property SLEW SLOW [get_ports {O_NAND_CH7_CE[5]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH7_CE[5]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH7_CE[5]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH7_CE[6]}]
set_property PACKAGE_PIN F13 [get_ports {O_NAND_CH7_CE[6]}]
set_property SLEW SLOW [get_ports {O_NAND_CH7_CE[6]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH7_CE[6]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH7_CE[6]}]

set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CH7_CE[7]}]
set_property PACKAGE_PIN E12 [get_ports {O_NAND_CH7_CE[7]}]
set_property SLEW SLOW [get_ports {O_NAND_CH7_CE[7]}]
#set_property DRIVE 8 [get_ports {O_NAND_CH7_CE[7]}]
#set_property PIO_DIRECTION BIDIR [get_ports {O_NAND_CH7_CE[7]}]

set_property IOSTANDARD SSTL18_II [get_ports O_NAND_CH7_CLE]
set_property PACKAGE_PIN F15 [get_ports O_NAND_CH7_CLE]
set_property SLEW FAST [get_ports O_NAND_CH7_CLE]
#set_property DRIVE 8 [get_ports O_NAND_CH7_CLE]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH7_CLE]

set_property IOSTANDARD SSTL18_II [get_ports O_NAND_CH7_ALE]
set_property PACKAGE_PIN F14 [get_ports O_NAND_CH7_ALE]
set_property SLEW FAST [get_ports O_NAND_CH7_ALE]
#set_property DRIVE 8 [get_ports O_NAND_CH7_ALE]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH7_ALE]

set_property IOSTANDARD SSTL18_II [get_ports O_NAND_CH7_WE]
set_property PACKAGE_PIN E13 [get_ports O_NAND_CH7_WE]
set_property SLEW FAST [get_ports O_NAND_CH7_WE]
#set_property DRIVE 8 [get_ports O_NAND_CH7_WE]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH7_WE]

set_property IOSTANDARD DIFF_SSTL18_II [get_ports O_NAND_CH7_RE_P]
set_property PACKAGE_PIN F17 [get_ports O_NAND_CH7_RE_P]
set_property SLEW FAST [get_ports O_NAND_CH7_RE_P]
#set_property DRIVE 8 [get_ports O_NAND_CH7_RE_P]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH7_RE_P]

set_property IOSTANDARD DIFF_SSTL18_II [get_ports O_NAND_CH7_RE_N]
set_property PACKAGE_PIN E17 [get_ports O_NAND_CH7_RE_N]
set_property SLEW FAST [get_ports O_NAND_CH7_RE_N]
#set_property DRIVE 8 [get_ports O_NAND_CH7_RE_N]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH7_RE_N]

set_property IOSTANDARD DIFF_SSTL18_II [get_ports IO_NAND_CH7_DQS_P]
set_property PACKAGE_PIN D15 [get_ports IO_NAND_CH7_DQS_P]
set_property SLEW FAST [get_ports IO_NAND_CH7_DQS_P]
#set_property DRIVE 8 [get_ports IO_NAND_CH7_DQS_P]
#set_property PIO_DIRECTION BIDIR [get_ports IO_NAND_CH7_DQS_P]

set_property IOSTANDARD DIFF_SSTL18_II [get_ports IO_NAND_CH7_DQS_N]
set_property PACKAGE_PIN D14 [get_ports IO_NAND_CH7_DQS_N]
set_property SLEW FAST [get_ports IO_NAND_CH7_DQS_N]
#set_property DRIVE 8 [get_ports IO_NAND_CH7_DQS_N]
#set_property PIO_DIRECTION BIDIR [get_ports IO_NAND_CH7_DQS_N]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH7_RB[0]}]
set_property PACKAGE_PIN K13 [get_ports {I_NAND_CH7_RB[0]}]
set_property SLEW FAST [get_ports {I_NAND_CH7_RB[0]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH7_RB[0]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH7_RB[0]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH7_RB[1]}]
set_property PACKAGE_PIN J14 [get_ports {I_NAND_CH7_RB[1]}]
set_property SLEW FAST [get_ports {I_NAND_CH7_RB[1]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH7_RB[1]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH7_RB[1]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH7_RB[2]}]
set_property PACKAGE_PIN H14 [get_ports {I_NAND_CH7_RB[2]}]
set_property SLEW FAST [get_ports {I_NAND_CH7_RB[2]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH7_RB[2]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH7_RB[2]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH7_RB[3]}]
set_property PACKAGE_PIN K15 [get_ports {I_NAND_CH7_RB[3]}]
set_property SLEW FAST [get_ports {I_NAND_CH7_RB[3]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH7_RB[3]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH7_RB[3]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH7_RB[4]}]
set_property PACKAGE_PIN J15 [get_ports {I_NAND_CH7_RB[4]}]
set_property SLEW FAST [get_ports {I_NAND_CH7_RB[4]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH7_RB[4]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH7_RB[4]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH7_RB[5]}]
set_property PACKAGE_PIN J16 [get_ports {I_NAND_CH7_RB[5]}]
set_property SLEW FAST [get_ports {I_NAND_CH7_RB[5]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH7_RB[5]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH7_RB[5]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH7_RB[6]}]
set_property PACKAGE_PIN B12 [get_ports {I_NAND_CH7_RB[6]}]
set_property SLEW FAST [get_ports {I_NAND_CH7_RB[6]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH7_RB[6]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH7_RB[6]}]

set_property IOSTANDARD SSTL18_II [get_ports {I_NAND_CH7_RB[7]}]
set_property PACKAGE_PIN C12 [get_ports {I_NAND_CH7_RB[7]}]
set_property SLEW FAST [get_ports {I_NAND_CH7_RB[7]}]
#set_property DRIVE 8 [get_ports {I_NAND_CH7_RB[7]}]
#set_property PIO_DIRECTION BIDIR [get_ports {I_NAND_CH7_RB[7]}]

set_property IOSTANDARD LVCMOS18 [get_ports O_NAND_CH7_WP]
set_property PACKAGE_PIN C14 [get_ports O_NAND_CH7_WP]
set_property SLEW SLOW [get_ports O_NAND_CH7_WP]
#set_property DRIVE 8 [get_ports O_NAND_CH7_WP]
#set_property PIO_DIRECTION BIDIR [get_ports O_NAND_CH7_WP]
